### ISSUE TITLE
Bump the plugin version?

### ISSUE THREAD

**Issue by mfojtik** [jenkinsci/kubernetes-plugin#15]
@carlossg would it be possible to bump the plugin version? I really need the bearer auth token support and was pushed recently and I don't want to bundle the plugin in my docker image repo ;-) Many thanks!

**Comment by ndeloof** [comment]
I can release the plugin if you wish. 
but would like to know if https://github.com/ndeloof/kubernetes-plugin/tree/ServiceAccount is a reasonable solution so it could be included.

**Comment by ndeloof** [comment]
as a side note : better to join jenkins-dev for such discussion

**Comment by mfojtik** [comment]
@ndeloof yeah I would wait for the ServiceAccount patch to be included in the release :-)
