### ISSUE TITLE
Allow slaves to use docker

### ISSUE THREAD

**Issue by thesamet** [jenkinsci/kubernetes-plugin#19]
It would be nice to have a setting that allows the slave POD to mount the host docker binary and socket inside the container.

Will you take a pull request for this?

**Comment by carlossg** [comment]
definitely

**Comment by thesamet** [comment]
I tried a few things and I think it will be more useful to actually give users configuration to mount anything (not just the host's docker socket). Though there are some many mounting options in Kubernetes. Maybe it would be even better instead to give some way to let users directly provide the PodSpec in JSON or YAML.

WDYT?

**Comment by carlossg** [comment]
Providing the PodSpec is a good option, but needs to be parsed by the plugin, the jenkins vars injected, and then sent to the kubernetes api.
Then there is the management of the template, should be stored as text? link to a url with the template (ie. git repo)?
Either that or add fields for Volumes and VolumeMounts

**Comment by flandr** [comment]
I'm also quite interested in having access to the Docker socket as well as other arbitrary contents of the host file system in containers running in this plugin. Obviously this feature could be a lot more complicated than the `volumes` configuration parameter of the [docker plugin](https://github.com/jenkinsci/docker-plugin) because of the wealth of volume types in Kubernetes, but an initial pass that just allowed specification of `hostPath` volumes would be sufficient. @thesamet, are you still working on this?

**Comment by thesamet** [comment]
I have something that works pretty good here. Will clean it up and send as
PR in the next few days.

On Wed, Oct 21, 2015 at 8:28 AM, Nate Rosenblum <notifications@github.com>
wrote:

> I'm also quite interested in having access to the Docker socket as well as
> other arbitrary contents of the host file system in containers running in
> this plugin. Obviously this feature could be a lot more complicated than
> the volumes configuration parameter of the docker plugin
> <https://github.com/jenkinsci/docker-plugin> because of the wealth of
> volume types in Kubernetes, but an initial pass that just allowed
> specification of hostPath volumes would be sufficient. @thesamet
> <https://github.com/thesamet>, are you still working on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jenkinsci/kubernetes-plugin/issues/19#issuecomment-149932491>
> .
>



-- 
-Nadav

**Comment by flandr** [comment]
Awesome, I look forward to it.

**Comment by thesamet** [comment]
@carlossg can you give feedback on this commit? Would love to get it in.

**Comment by bdefeyter** [comment]
FWIW, as a user pulling in @thesmet's branch to get this functionality.. I would also really like to see this merged :)
