### ISSUE TITLE
create Pods/Jobs for different kind of docker image using Jenkins Workflow?

### ISSUE THREAD

**Issue by jstrachan** [jenkinsci/kubernetes-plugin#25]
it would be great if we could use something like this in the Jenkins Workflow DSL
```
slave("maven:3.3.1") { 
  ...
}

or

node(nameOfDockerImage) { 
...
}
```
and under the covers the kubernetes plugin would ensure there's enough pods for the RC for the given docker image running; scaling up/down the RCs for each kind of slave.

i.e. each time you use a docker image name in the DSL in a jenkins workflow script; under the covers it lazily creates an RC for the docker image name if there is not one already; then scales the relevant RC up to ensure there's always at least 1 pending slave.

Then if your jenkins workflow scripts use, say, 2 docker images - nodejs and maven - when you ran your workflow build there'd be 2 RCs for nodejs and maven which each represent a slave group and they'd auto-scale up/down based on the number of pending builds

**Comment by carlossg** [comment]
The plugin is not creating RCs, just creating pods on demand, one for each job, also isolating executions. The problem with RCs is that after a job you need to target a specific pod for termination, so having an RC doesn't really help.
I'm looking forward to using `Job` in Kubernetes 1.1, which seems more fitted to the Jenkins slave use case

**Comment by jstrachan** [comment]
Ah OK - yeah creating a Pod/Job on demand would rock. Please ignore all use of RC above ;)

Does it seem easily possible that we could just pass in the docker image name (and maybe env vars too) using the Jenkins Workflow DSL? Then we'd kinda have something like the Docker Workflow model; but where each docker image used in the Workflow DSL just ends up creating a Pod/Job on demand? Its sounding awesome!

**Comment by jstrachan** [comment]
@carlossg I wonder how jenkins workflow should use the kubernetes plugin slave model so that the workflow can pass in the docker image to use? I'd love a Jenkinsfile to have the details of what docker images to use by the slaves. I wonder if we use a naming convention for labels to indicate the label is a docker image name? 

e.g.
```
node("docker:maven:3.3.1") {
  git http://acme.com
  sh "mvn deploy"
}
```
which would mean to use the docker image `maven:3.3.1` to run the slave job?

**Comment by carlossg** [comment]
ping @jglick

**Comment by waprin** [comment]
This is pretty much exactly what I'm looking for as well. I am going to work on something like it unless someone else has beaten me to it.

**Comment by jstrachan** [comment]
Already done it you wanna reuse it!

https://github.com/fabric8io/kubernetes-workflow

**Comment by carlossg** [comment]
Moved to https://issues.jenkins-ci.org/browse/JENKINS-33344
