### ISSUE TITLE
Documentation request: "Setup Kubernetes CLI (kubectl)"

### ISSUE THREAD

**Issue by anthonator** [jenkinsci/kubernetes-plugin#36]
I'm curious what the purpose of the "Setup Kubernetes CLI (kubectl)" option under Build Environment within a project config is. Is this necessary for the plugin to provision a slave?

Some documentation on this would be appreciated.

**Comment by stvnwrgs** [comment]
+1

**Comment by listx** [comment]
From my experience no, that is not necessary to get slaves provisioned. But I am also curious about what the option does.

**Comment by innovia** [comment]
from what i played with - this will basically create a kube/config file in the workspace and only be called when the jenkins master #of executers is > 0 

i think it will allow to use the job bash script to call the kubectl create -f your_pod template and then launch the slave but im not so sure
