### ISSUE TITLE
Allow running Docker commands - mount in the socket

### ISSUE THREAD

**Issue by jhgaylor** [jenkinsci/kubernetes-plugin#40]
I would like to be able to do a HostPath volume mount of the docker socket from the k8s node into my build slave so that I can build images and push them to a registry.

Is this something that could get patched quickly? I know no Java so this is kind of daunting to me. I think I could patch it so that every container has that socket mounted but not to make it an option.

Thoughts?

**Comment by bdefeyter** [comment]
Support for this was merged in https://github.com/jenkinsci/kubernetes-plugin/pull/31

Any chance there will be a new release cut soon?

**Comment by carlossg** [comment]
0.5 has been released
