### ISSUE TITLE
Is there any way to deploy jenkins slaves to specific Kubenetes nodes?

### ISSUE THREAD

**Issue by yhung124** [jenkinsci/kubernetes-plugin#42]
Hi @carlossg ,
Is there any way to deploy jenkins slaves to specific K8S nodes?
In YAML or JSON configure file of Kubenetes, we can use "nodeSelector" tag to specify nodes to deploy.
How should I do that in jenkins-kubernetes-plugin?
Thanks!~

**Comment by yhung124** [comment]
Answer the question by myself, just merge the pull request of the following.
https://github.com/jenkinsci/kubernetes-plugin/pull/34

**Comment by carlossg** [comment]
Will handle with #34
