### ISSUE TITLE
custom pod template that inlcudes in it the jenkins slave image

### ISSUE THREAD

**Issue by innovia** [jenkinsci/kubernetes-plugin#47]
HI @carlossg 

we have a need to isolate in tests redis mysql and other databases per build

im looking for a way to feed the plugin my own pod template, so that it brings up all the services and the jenkins_slave defined in that pod template

how can we do that?

**Comment by listx** [comment]
Configure -> Cloud -> Images -> Add Pod Template -> Kubernetes Pod Template? It's in the README's screenshot.

**Comment by innovia** [comment]
@listx nope that would bring up a new pod definition using an image you specify in that template 

in other words this pod template constructs a pod definition (in fabric8) that will be passed to k8 cluster as an object not an actual file

**Comment by marcolenzo** [comment]
I was going to open a very similar issue.

When performing a build you might have tests which do execute calls to databases or other middleware.

Currently I was forced to create a docker image which contains both the jnlp-slave and my middleware. However it is a shame since Kubernetes gives us the possibility of grouping containers in one Pod which represents a sort of logical host.

That said I would advocate to either allow the definition of multiple containers within the configuration of the Pod Template. An option would be to let users define their own POD in YAML and feed it to the kubectl.

**Comment by listx** [comment]
I think the issue would be better named as "Allow multi-container pod template".

**Comment by innovia** [comment]
I was able to add a code that allow to read a Template but it doesn't cover
all the options yet

Basically this plugin utilize the fabric8 framework and the pod is composed
of Api blocks that builds a pod


So for every section in the yml config I had to create the api block

I will complete it soon with the option to have a file path in the pod
template

If you know Java I can share the code when with you so you can help me add
the missing specs there are many many options to loop over and convert to
api objects to build the pod, so at the moment I only did the basics:

Spec
Volumes (hostpath and emptydir)
Containers
Env array
Ports (container ports)
Volumes
Image



I'm still missing
Health checks
Labels
Other volumes types
And other stuff I didn't go over every option in the api doc

Ami

On יום ד׳, 3 בפבר׳ 2016 at 7:07 Linus <notifications@github.com> wrote:

> I think the issue would be better named as "Allow multi-container pod
> template".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jenkinsci/kubernetes-plugin/issues/47#issuecomment-179013454>
> .
>
-- 
Ami Mahloof
DevOps Engineer
Glide

**Comment by innovia** [comment]
@carlossg i've been able to rewrite the plugin to parse my pod.json template however im in desperate need of help, can you please tell me what  to add to get the JOB_NAME and BUILD_ID build variables 

i've read the code so many times and can't understand how this not using the perform or build api,

could you please help me out?

thanks

Ami

**Comment by innovia** [comment]
@carlossg 
the only lead i had was the KubectlBuildWrapper but from what i saw this does not get called if jenkins number of executers is set to 0

if i set it to 1 and  the checkbox for Setup Kubectl on the job configuration, then yes i can get the job name from the build

```java
 public void setUp(Context context, Run<?, ?> build, FilePath workspace, Launcher launcher, TaskListener listener, EnvVars initialEnvironment) throws IOException, InterruptedException {
		LOGGER.log(Level.INFO, "BUILD STARTED");

    	// this seems to only run when jenkins num of executers > 0
    	EnvVars envVars = new EnvVars();
    	envVars = build.getEnvironment(listener);
		LOGGER.log(Level.INFO, "JOBNAME: " + envVars.get("JOB_NAME"));
    	
        FilePath configFile = workspace.createTempFile(".kube", "config");
		LOGGER.log(Level.INFO, "Setup build: " + build);

		LOGGER.log(Level.INFO, "Setup workspace: " + workspace);
```

maybe im not getting  something right?

**Comment by carlossg** [comment]
Moved to https://issues.jenkins-ci.org/browse/JENKINS-33347 please watch issue there
