### ISSUE TITLE
Allow passing of `--privileged=true` flag for slave images

### ISSUE THREAD

**Issue by listx** [jenkinsci/kubernetes-plugin#48]
I'd like to run the `docker build` command from my slave image, but in order for that to happen I need to run the slave image itself with the `--privileged=true` flag.

**Comment by mikesplain** [comment]
Just as an FYI I was able to build docker images inside the slave as long as you mount the docket socket into into the container and docker is installed in the image. Shouldn't require more than that. If you run CoreOS, you also need to mount `/usr/lib/libdevmapper.so.1.02`. Hope this helps.

**Comment by listx** [comment]
As for mounting the docker socket, I've seen this trick before (`docker run -it -v /var/run/docker.sock:/var/run/docker.sock foo`, see http://nathanleclaire.com/blog/2014/07/12/10-docker-tips-and-tricks-that-will-make-you-sing-a-whale-song-of-joy/) <--- I will try this and see what happens (I just noticed that there is a "Volume" box for the slave pod definition).

I also noticed that if I click on the "Advanced" button, I get a "privileged mode" checkbox for the slave containers, so my original description of this issue is probably a moot point.

**Comment by listx** [comment]
I got it to run docker commands from within the slave image, using your suggestions @mikesplain, thanks.
