### ISSUE TITLE
"Kubernetes Service Account" credential does not show up

### ISSUE THREAD

**Issue by listx** [jenkinsci/kubernetes-plugin#50]
After installing this plugin on a Jenkins master, after I click on "Add cloud" and then "Credentials" and "Add", I cannot see a Kind that says "Kubernetes Service Account".

Jenkins 1.645
Credentials Plugin 1.24
Kubernetes plugin 0.5

**Comment by carlossg** [comment]
This will only show when Jenkins master itself is deployed inside a Pod, please open issue in https://issues.jenkins-ci.org/browse/JENKINS if that's the case
