### ISSUE TITLE
Different images for different build jobs

### ISSUE THREAD

**Issue by marcolenzo** [jenkinsci/kubernetes-plugin#53]
There are scenarios where it could be useful to utilize a different container image/pod according to the job being executed. Currently I did not find a way to override to plugin configuration per job.

**Comment by listx** [comment]
I think you can do this already. Just add another cloud/pod definition and use a different label. You'll end up repeating yourself for a lot in the conifguration, but it should work.

**Comment by marcolenzo** [comment]
You are correct! My bad for not noticing the labels option.

I tested it out using the node selector plugin and it works perfect.

Thank you very much!
